; 金融Agent 安装程序 — NSIS Modern UI 2
; 方块编程公司 · 版本 1.0
; 由 WSL 端 makensis 编译：build_installer.sh

Unicode true
!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "StrFunc.nsh"
!include "nsDialogs.nsh"
!include "FileFunc.nsh"
${StrCase}
${StrRep}

; ------------------------------------------------------------------
; 产品信息
; ------------------------------------------------------------------
!define APP_NAME        "金融Agent"
!define APP_NAME_EN     "FinancialAgent"
!define APP_VERSION     "1.0"
!define APP_PUBLISHER   "方块编程公司"
!define APP_BAT         "金融Agent-Web.bat"
!define APP_SHORTCUT    "金融Agent"
!define APP_UNINST_KEY  "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME_EN}"

Name "${APP_NAME}"
OutFile "FinancialAgent-Setup.exe"
InstallDir "C:\FinancialAgent"
InstallDirRegKey HKLM "Software\${APP_NAME_EN}" "InstallLocation"
RequestExecutionLevel admin

; ------------------------------------------------------------------
; 版本信息（文件属性）
; ------------------------------------------------------------------
VIProductVersion "1.0.0.0"
VIAddVersionKey /LANG=2052 "ProductName" "${APP_NAME}"
VIAddVersionKey /LANG=2052 "CompanyName" "${APP_PUBLISHER}"
VIAddVersionKey /LANG=2052 "FileDescription" "${APP_NAME} 安装程序"
VIAddVersionKey /LANG=2052 "FileVersion" "${APP_VERSION}"
VIAddVersionKey /LANG=2052 "LegalCopyright" "© ${APP_PUBLISHER}"

; ------------------------------------------------------------------
; MUI 2 配置
; ------------------------------------------------------------------
!define MUI_ICON   "icon.ico"
!define MUI_UNICON "icon.ico"
!define MUI_ABORTWARNING
!define MUI_FINISHPAGE_RUN      "$INSTDIR\${APP_BAT}"
!define MUI_FINISHPAGE_RUN_TEXT "立即运行 ${APP_NAME}（启动 Web 界面）"
!define MUI_FINISHPAGE_TEXT "安装完成！$\r$\n$\r$\n如需启动，请运行「${APP_BAT}」或双击桌面快捷方式。$\r$\n$\r$\n若未检测到 WSL2 环境，请先安装 WSL2 Ubuntu（wsl --install -d Ubuntu）后再运行。"

; 页面顺序：欢迎 → 许可 → WSL 检测 → 目录 → 组件 → 安装 → 完成
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "license.txt"
Page custom WSLPageCreate WSLPageLeave
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_LANGUAGE "SimpChinese"

; ------------------------------------------------------------------
; 变量与函数
; ------------------------------------------------------------------
Var WSL_MISSING

; WSL 检测页（目录页之前；无 WSL 可继续，完成页有提示）
Function WSLPageCreate
    !insertmacro MUI_HEADER_TEXT "环境检测" "检查 Windows Subsystem for Linux (WSL2)"
    nsDialogs::Create 1018
    Pop $0
    ${If} $0 == error
        Abort
    ${EndIf}

    ${If} ${FileExists} "$WINDIR\System32\wsl.exe"
        StrCpy $WSL_MISSING "0"
        ${NSD_CreateLabel} 0 10u 100% 30u "✓ 已检测到 WSL (wsl.exe)。$\r$\n金融Agent 需要在 WSL2 Ubuntu 中运行 Python 服务，请确保已安装 Ubuntu 发行版。"
        Pop $1
    ${Else}
        StrCpy $WSL_MISSING "1"
        ${NSD_CreateLabel} 0 10u 100% 50u "⚠ 未检测到 WSL（Windows Subsystem for Linux）。$\r$\n$\r$\n金融Agent 依赖 WSL2 + Ubuntu 运行 Python 服务，请先安装：$\r$\n  1. 以管理员身份打开 PowerShell$\r$\n  2. 执行: wsl --install -d Ubuntu$\r$\n  3. 重启电脑$\r$\n$\r$\n您可以继续安装，但安装完成后需先装好 WSL2 才能运行。"
        Pop $1
    ${EndIf}

    nsDialogs::Show
FunctionEnd

Function WSLPageLeave
    ; 允许继续安装（无论 WSL 是否存在）
FunctionEnd

; Windows 路径 → WSL 路径: C:\FinancialAgent → /mnt/c/FinancialAgent
; 入栈: Windows 路径; 出栈: WSL 路径（已转义，含空格安全）
Function WinToWslPath
    Exch $0
    Push $1
    Push $2
    ; $0 = C:\xxx
    StrCpy $1 $0 1 0                    ; 盘符 "C"
    ${StrCase} $1 $1 "L"                ; 转小写 "c"
    StrCpy $2 $0 "" 2                   ; 去掉 "C:"
    ${StrRep} $2 $2 "\" "/"             ; 反斜杠 → 正斜杠
    StrCpy $0 "/mnt/$1$2"               ; /mnt/c/xxx
    ; 去除尾部斜杠（避免 /mnt/c/xxx/ 形式）
    StrCpy $1 $0 "" -1
    ${If} $1 == "/"
        StrCpy $0 $0 -1
    ${EndIf}
    Pop $2
    Pop $1
    Exch $0
FunctionEnd

; ------------------------------------------------------------------
; 安装 Section
; ------------------------------------------------------------------
Section "金融Agent 主程序（必装）" SecMain
    SectionIn RO
    SetOutPath "$INSTDIR"

    ; 打包内容（build_installer.sh 收集到 stage 目录）
    File /r "${STAGE}/*"

    ; 生成 金融Agent-Web.bat（纯 ASCII）
    Push $INSTDIR
    Call WinToWslPath
    Pop $0
    FileOpen $1 "$INSTDIR\${APP_BAT}" w
    FileWrite $1 "@echo off$\r$\n"
    FileWrite $1 "rem FinancialAgent Web launcher - generated by installer$\r$\n"
    FileWrite $1 "wsl bash -c $\"cd '$0' && bash run.sh$\"$\r$\n"
    FileClose $1

    ; 卸载器
    WriteUninstaller "$INSTDIR\Uninstall.exe"

    ; 标准注册（卸载表 + 添加/删除程序）
    WriteRegStr HKLM "${APP_UNINST_KEY}" "DisplayName" "${APP_NAME}"
    WriteRegStr HKLM "${APP_UNINST_KEY}" "DisplayVersion" "${APP_VERSION}"
    WriteRegStr HKLM "${APP_UNINST_KEY}" "Publisher" "${APP_PUBLISHER}"
    WriteRegStr HKLM "${APP_UNINST_KEY}" "InstallLocation" "$INSTDIR"
    WriteRegStr HKLM "${APP_UNINST_KEY}" "UninstallString" "$\"$INSTDIR\Uninstall.exe$\""
    WriteRegStr HKLM "${APP_UNINST_KEY}" "DisplayIcon" "$INSTDIR\icon.ico"
    WriteRegDWORD HKLM "${APP_UNINST_KEY}" "NoModify" 1
    WriteRegDWORD HKLM "${APP_UNINST_KEY}" "NoRepair" 1
    ${GetSize} "$INSTDIR" "/S=0K" $2 $3 $4
    WriteRegDWORD HKLM "${APP_UNINST_KEY}" "EstimatedSize" $2
    WriteRegStr HKLM "Software\${APP_NAME_EN}" "InstallLocation" "$INSTDIR"
    WriteRegStr HKLM "Software\${APP_NAME_EN}" "WslPath" "$0"
SectionEnd

Section "创建桌面快捷方式" SecDesktop
    CreateShortCut "$DESKTOP\${APP_SHORTCUT}.lnk" "$INSTDIR\${APP_BAT}" "" "$INSTDIR\icon.ico"
SectionEnd

; ------------------------------------------------------------------
; 卸载 Section
; ------------------------------------------------------------------
Section "Uninstall"
    ; 删除快捷方式
    Delete "$DESKTOP\${APP_SHORTCUT}.lnk"

    ; 删除安装目录
    RMDir /r "$INSTDIR"

    ; 删除注册表
    DeleteRegKey HKLM "${APP_UNINST_KEY}"
    DeleteRegKey HKLM "Software\${APP_NAME_EN}"
SectionEnd
